name: Docker Image CI

on: 
  push:
    branches:
      - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master
    - name: createPublicSSHKeyFile
      run: |
        echo ${{ secrets.PUBLIC_SSH_KEY }} > ./testing.pub
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag debugger:latest
        docker tag debugger:latest debugger:$(date +%s)
