name: Docker Image CI

on: 
  push:
    branches:
      - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master
    - name: createPublicSSHKeyFile
      run: |
        echo ${{ secrets.PUBLIC_SSH_KEY }} > ./testing.pub
    - name: Build the Docker image
      env:
        REGISTRY: docker.pkg.github.com
        REPOSITORY: $REGISTRY/$GITHUB_REPOSITORY/debugger
      run: |
        docker build . --file Dockerfile --tag $REPOSITORY:latest
        docker tag $REPOSITORY:latest $REPOSITORY:$(date +%s)
        docker login -u ${{ secrets.GITHUB_DOCKER_PUSH_USER }} -p ${{ secrets.GITHUB_DOCKER_PUSH_PASSWD }} $REGISTRY
        docker push $REPOSITORY

